### ISSUE TITLE
Reference to FluidValidation 7.1.0

### ISSUE THREAD

**Issue by nickoli4** [VirtoCommerce/vc-module-catalog-csv-import#16]
Hi,

Is the reference to the FluidValidation nuget package in the Data, Web and Test project necessary? If so, can/should it be updated to match the version referenced by the catalog module? (7.5.2). We use the latest release for both modules and they are referencing a different version.

Thanks in advance,

Nick Olivier

**Comment by ksavosteev** [comment]
v1.0.10
