### ISSUE TITLE
import category SEO data

### ISSUE THREAD

**Issue by pungiish** [VirtoCommerce/vc-module-catalog-csv-import#17]
I am working on building a new store, which has a lot of categories.
It'd be a lot faster to add the funcionality to import SEO data of all the categories of products,
because otherwise, you have to manually click every one of them and pasting the data.

**Comment by tatarincev** [comment]
We have now https://github.com/VirtoCommerce/vc-module-catalog-bulk-action module and are working on the import functionality that will simplify the bulk editing process.
