### ISSUE TITLE
Importer incorrectly displays number of errors

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-module-catalog-csv-import#20]
When importing large number of items for all rows have errors (for instance, non-existant pricelist ID) the importer would say 150 out of 2500 items failed (have errors) instead of all items have errors. 

Makes it hard to troubleshoot what went wrong..

After several retries and weeks of experience with VC we now know this is how it works and that it is a possibility all imports failed but in the future it'd be nice if the count was correct.

Another thing, the items do get imported even if pricelist doesn't exist which I don't think is the right behaviour when pricelist ID was specified in the CSV. 

I'd agree though to import them if pricelist ID field was empty.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
