### ISSUE TITLE
Catalog Export: Select price list dropdown is always empty

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce/vc-module-catalog-csv-import#27]
![image](https://user-images.githubusercontent.com/20122385/59095487-ed010c00-8918-11e9-8d20-bd1e63085ca6.png)

API pricelist request looks good so it's an UI issue
![image](https://user-images.githubusercontent.com/20122385/59095621-479a6800-8919-11e9-8ea9-8d5407f177f7.png)

**Comment by yecli** [comment]
Price lists combo is filled with catalog price lists, prices exported based on selected price list.

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/tag/v1.1.4
