### ISSUE TITLE
Importing multiple images, SEO data for categories

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-module-catalog-csv-import#35]
Hey guys, we have made some changes to the importer a while back and we're having hard time keeping it up to date with changes you make so I was wondering if you'd be interested in integrating our changes. 

Mostly the two features added are:
1. when creating categories add SEO details for them (commit https://github.com/brgrz/vc-module-catalog-csv-import/commit/c079d07d2d738ea71562161f95bc51a4646e1edd),
2. importing multiple images for product, by using spaces in PrimaryImage field and specifying multiple files (commit https://github.com/brgrz/vc-module-catalog-csv-import/commit/5ac1a9288c9dcec1c94259d6814309f0162b4901)

Some minor fixes were also done after those two commits. 

Do you see this could be merged into the importer module or not? Or would you consider implementing it yourself (we could also alter our implementation per your suggestions)

@yecli

**Comment by tatarincev** [comment]
@brgrz  Please don't hesitate to make a PR, then we'll figure it out

**Comment by yecli** [comment]
We've implemented an ability to import multiple images:
https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/tag/v1.1.6
