### ISSUE TITLE
CSV file content doesn't change when exporting a catalog

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-catalog-csv-import#36]
Every time I export a catalog to a CSV file I get the same file content.

### Steps to reproduce
1. Navigate to https://admin-demo.virtocommerce.com
2. Export any catalog to a CSV file and download the file.
3. Change any product in this catalog and save changes.
4. Export this catalog again and download the file. Result: the file is the same as the first one.

Version info: 
- Browser version: Version 76.0.3809.132 (Official Build) (64-bit)
- Platform version: 2.13.49
- Module version: 1.1.4

**Comment by yecli** [comment]
@artem-dudarev Am I getting right the problem could be in export result file caching on server side (like IIS caching), and the problem will be solved by introducing setting with export template file name for CSV module like this one?
![image](https://user-images.githubusercontent.com/15610352/65437404-295f6600-de3d-11e9-84fd-d166683d5d72.png)

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/tag/v1.1.5
