### ISSUE TITLE
VirtoCommerce.CatalogCsvImportModule.dll not found exception

### ISSUE THREAD

**Issue by EmreKarahan** [VirtoCommerce/vc-module-catalog-csv-import#76]
**VirtoCommerce.CatalogCsvImportModule_3.18.0.zip** doesn't contain **VirtoCommerce.CatalogCsvImportModule.dll**

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7382 has been created

**Comment by OlegoO** [comment]
@EmreKarahan Thank you very much for the feedback. We are fixing the release. 
As a workaround: Remove the module or install https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/download/3.15.0/VirtoCommerce.CatalogCsvImportModule_3.15.0.zip

**Comment by OlegoO** [comment]
Please download and install
https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/tag/3.18.0
